<?php
use Mageplaza\LazySpeaker\Block\ProcessForm;
/** @var ProcessForm $block */
$wordId = $block->getRequest()->getParam('word');
$wordData = $block->helperData->getWordData($wordId);
?>
<div class="row">
    <div class="col-4">
        <form name="addData" method="post" id="addData" class="form"
              action="<?= $block->getWordFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}' enctype="multipart/form-data">
            <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
            <fieldset class="fieldset">
                <legend class="legend">
                    <span><?= $block->escapeHtmlAttr(__('Edit word')) ?></span>
                </legend>
                <fieldset class="fieldset row">
                    <div class="fields col-4 bg-primary">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Từ')) ?></span></label>
                            <div class="control">
                                <input name="word" id="word" title="Word" class="input-text" type="text"
                                       data-validate="{required:true}"
                                       value="<?= $wordData['word'] ?>">
                            </div>
                        </div>
                        <div class="field file-uploader-image">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Ảnh')) ?></span></label>
                            <div class="control">
                                <input name="image" id="image" title="Image" class="input-file" type="file">
                            </div>
                        </div>
                        <div class="field select">
                            <label class="label" for="title">
                                <span><?= $block->escapeHtmlAttr(__('Từ loại')) ?></span>
                            </label>
                            <div class="control">
                                <select name="word_class" id="word_class" class="col-2">
                                    <?php foreach ($block->getOptionWordClass() as $opt): ?>
                                        <?php if($wordData['word_class'] == $opt['value']): ?>
                                            <option value="<?= $opt['value'] ?>" selected><?= $opt['label'] ?></option>
                                        <?php else : ?>
                                            <option value="<?= $opt['value'] ?>"><?= $opt['label'] ?></option>
                                        <?php endif ?>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title">
                                <span><?= $block->escapeHtmlAttr(__('Nghĩa')) ?></span>
                            </label>
                            <div class="control">
                                <textarea name="meaning" id="meaning" title="Meaning"
                                          class="input-text validate-length" type="textarea"
                                          rows="4" cols="50"
                                          data-validate="{required:true, 'min_text_length':'1'}"
                                ><?= $wordData['meaning'] ?></textarea>
                            </div>
                        </div>
                        <div class="field name">
                            <label class="label" for="title">
                                <span><?= $block->escapeHtmlAttr(__('Câu ví dụ')) ?></span>
                            </label>
                            <div class="control">
                                <textarea name="sentence_example" id="sentence_example" title="Example Meaning"
                                          class="input-text" type="textarea" rows="4" cols="50"
                                ><?= $wordData['sentence_example'] ?></textarea>
                            </div>
                        </div>
                        <div class="field name">
                            <label class="label" for="title">
                                <span><?= $block->escapeHtmlAttr(__('Nghĩa câu ví dụ')) ?></span>
                            </label>
                            <div class="control">
                                <textarea name="sentence_meaning" id="sentence_meaning"
                                          title="Meaning Example Sentence" class="input-text"
                                          type="textarea" rows="4" cols="50"
                                ><?= $wordData['sentence_meaning'] ?></textarea>
                            </div>
                        </div>
                        <div class="field name">
                            <label class="label" for="title">
                                <span><?= $block->escapeHtmlAttr(__('Ghi chú')) ?></span>
                            </label>
                            <div class="control">
                                <textarea name="note" id="note"
                                          title="Note" class="input-text"
                                          type="textarea" rows="4" cols="50"
                                ><?= $wordData['note'] ?></textarea>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="word_id" value="<?= $wordId ?>">
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                            escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
